### ISSUE TITLE
deepcopy of WKB objects

### ISSUE THREAD

**Issue by mwiebusch78** [geoalchemy/geoalchemy2#120]
It seems that the WKBElement class doesn't work with deepcopy. When trying to make a deep copy of a WKBElement I get the error shown below. Having WKBElement objects support the deepcopy protocol would be a very useful feature.

  File "/opt/anaconda3/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 219, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/opt/anaconda3/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 300, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 246, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/opt/anaconda3/lib/python3.4/copy.py", line 295, in _reconstruct
    y = callable(*args)
  File "/opt/anaconda3/lib/python3.4/copyreg.py", line 88, in __newobj__
    return cls.**new**(cls, *args)
TypeError: Required argument 'object' (pos 1) not found

**Comment by elemoine** [comment]
Python 2's `buffer` objects and Python 3's `memoryview` objects are not compatible with `deepcopy`. Not sure what can be done about that.

Examples:

```
$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import copy
>>> copy.deepcopy(buffer('test'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/home/elemoine/.virtualenvs/geoalchemy2/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: buffer() takes at least 1 argument (0 given)
```

```
$ python3
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import copy
>>> copy.deepcopy(memoryview(bytes('test', 'UTF8')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: can't pickle memoryview objects
```
