### ISSUE TITLE
geoalchemy2 does not create geom column for spatialite

### ISSUE THREAD

**Issue by mullenkamp** [geoalchemy/geoalchemy2#196]
Hi,

I went through the very nice spatialite tutorial provided by your documentation:
https://geoalchemy-2.readthedocs.io/en/latest/spatialite_tutorial.html

Unfortunately it doesn't appear that the geom column gets created as the step:
`our_lake = session.query(Lake).filter_by(name='Majeur').first()`
returns...
`OperationalError: (sqlite3.OperationalError) no such column: lake.geom [SQL: 'SELECT lake.id AS lake_id, lake.name AS lake_name, AsEWKB(lake.geom) AS lake_geom \nFROM lake \nWHERE lake.name = ?\n LIMIT ? OFFSET ?'] [parameters: ('Majeur', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)`

I'm using:
geoalchemy 0.5.0
sqlalchemy 1.2.8
sqlite 3.20.1

Thanks.

**Comment by elemoine** [comment]
Could you please provide more code. The way you set up the class/table is key for example.

**Comment by mullenkamp** [comment]
It's exactly as the tutorial is written, but I will write it out when I get back to a computer on Sunday.

**Comment by elemoine** [comment]
Your example runs fine in my case (with `'mod_spatialite'` replaced by `'/usr/lib/x86_64-linux-gnu/mod_spatialite.so'` in the `load_extension` call).

What SpatiaLite version do you have? Are you sure you don't have errors before the `OperationalError` on the SELECT query?

**Comment by mullenkamp** [comment]
Interesting...Running it fresh with the lines I wrote above fails initially at the `session.commit()`, although I must have gotten through this to the next line in the past...
This new error at the `session.commit()` is :
`OperationalError: (sqlite3.OperationalError) no such table: main.idx_lake_geom [SQL: 'INSERT INTO lake (name, geom) VALUES (?, GeomFromEWKT(?))'] [parameters: ('Majeur', 'POLYGON((0 0,1 0,1 1,0 1,0 0))')] (Background on this error at: http://sqlalche.me/e/e3q8)`

But when I open the file in DB Browser, it shows that there's a table called lake...
I'm running libspatialite 4.3.0a on a windows machine.

I've run through an old tutorial from the original sptialite author when he used a python package and his tutorial runs fine on my python environment:
http://www.gaia-gis.it/spatialite-2.4.0-4/splite-python.html

Sorry for the difficulties...

**Comment by mullenkamp** [comment]
Hopefully this will make it totally reproducible...

Build the conda env:
`conda create -n geo1 geoalchemy2 python=3.6 libspatialite`

<br/>
Environment (<code>conda list</code>):
<details>

```
# Name                    Version                   Build  Channel
certifi                   2018.8.24                py36_0    conda-forge
freexl                    1.0.2                    vc14_2  [vc14]  conda-forge
geoalchemy2               0.5.0                      py_0    conda-forge
geos                      3.4.2                    vc14_2  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_11  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
pip                       18.0                     py36_1    conda-forge
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
python                    3.6.6                he025d50_0    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
sqlalchemy                1.2.11           py36hfa6e2cd_0    conda-forge
sqlite                    3.13.0                   vc14_0  [vc14]  conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
wincertstore              0.2                      py36_2    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
active environment : geo1
    active env location : E:\programs\anaconda3_64bit\envs\geo1
            shell level : 2
       user config file : C:\Users\michaelek\.condarc
 populated config files : C:\Users\michaelek\.condarc
          conda version : 4.5.11
    conda-build version : 3.11.0
         python version : 3.6.6.final.0
       base environment : E:\programs\anaconda3_64bit  (writable)
           channel URLs : https://conda.anaconda.org/mullenkamp/win-64
                          https://conda.anaconda.org/mullenkamp/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : E:\programs\anaconda3_64bit\pkgs
                          C:\Users\michaelek\AppData\Local\conda\conda\pkgs
       envs directories : E:\programs\anaconda3_64bit\envs
                          C:\Users\michaelek\AppData\Local\conda\conda\envs
                          C:\Users\michaelek\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

Run the code exactly as I wrote it in the previous message...and you get...

```
Traceback (most recent call last):
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: main.idx_lake_geom

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ecan\git\HydroPandas\users\MK\tests\geoalchemy2_test.py", line 49, in <module>
    session.commit()
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\session.py", line 943, in commit
    self.transaction.commit()
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\session.py", line 467, in commit
    self._prepare_impl()
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\session.py", line 447, in _prepare_impl
    self.session.flush()
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
    self._flush(objects)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
    raise value
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\session.py", line 2344, in _flush
    flush_context.execute()
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
    rec.execute(self)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 556, in execute
    uow
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\orm\persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "E:\programs\anaconda3_64bit\envs\geo1\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: main.idx_lake_geom [SQL: 'INSERT INTO lake (name, geom) VALUES (?, GeomFromEWKT(?))'] [parameters: ('Majeur', 'POLYGON((0 0,1 0,1 1,0 1,0 0))')] (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by adrien-berchet** [comment]
Closed because we are not able to reproduce the issue and because of a lack of activity.
Feel free to reopen it if needed.
