### ISSUE TITLE
type "geometry" does not exist when using schema other than Public with PostGIS

### ISSUE THREAD

**Issue by dangelsaurus** [geoalchemy/geoalchemy2#201]
Using postgis, I'm getting an error when using a schema other than public.

```
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
from geoalchemy2 import Geometry
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

class Lake(Base):
     __tablename__ = 'lake'
     id = Column(Integer, primary_key=True)
     name = Column(String)
     geom = Column(Geometry('POLYGON'))


engine = create_engine("postgresql://postgres:postgres@localhost/cc1",
                       connect_args={'options': '-csearch_path={}'.format('usda')}, echo=True)



Session = sessionmaker(bind=engine)
session = Session()
Base.metadata.create_all(engine)
```

fails with

```
Traceback (most recent call last):
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: type "geometry" does not exist
LINE 5:  geom geometry(POLYGON,-1), 
              ^


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "C:/Users/user1/Dropbox/cc1/cc1/default/db/test.py", line 23, in <module>
    Base.metadata.create_all(engine)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\sql\schema.py", line 4005, in create_all
    tables=tables)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\sql\ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\sql\ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\sql\ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 1009, in _execute_ddl
    compiled
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\Users\user1\.virtualenvs\cc1-OYrwG_on\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) type "geometry" does not exist
LINE 5:  geom geometry(POLYGON,-1), 
              ^
 [SQL: '\nCREATE TABLE lake (\n\tid SERIAL NOT NULL, \n\tname VARCHAR, \n\tgeom geometry(POLYGON,-1), \n\tPRIMARY KEY (id)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)

Process finished with exit code 1
```

however simply running

```
CREATE TABLE usda.lake (
	id SERIAL NOT NULL, 
	name VARCHAR, 
	geom geometry(POLYGON,-1), 
	PRIMARY KEY (id)
)
```

works correctly.

as does changing `...format('usda')` to `...format('public')`

**Comment by elemoine** [comment]
Have you tried using

```py
class Lake(Base):
    __tablename__ = 'lake'
    __table_args__ = {'schema': 'usda'}
```

instead of setting the search_path on the connections?
