### ISSUE TITLE
WKBElement construct has no default compilation handler

### ISSUE THREAD

**Issue by mam8cc** [geoalchemy/geoalchemy2#213]
Using `geoalchemy==0.6.1` appears to introduce a regression for some versions of `SQLAlchemy` (`< 1.1.0`, tested `1.0.12` through `1.0.18`).

```
$ python run.py
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 456, in __call__
    fn = self.specs['default']
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 56, in <module>
    session.commit()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 797, in _emit_insert_statements
    params)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in _execute_clauseelement
    inline=len(distilled_params) > 1)
  File "<string>", line 1, in <lambda>
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 500, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 395, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 190, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 1823, in visit_insert
    crud_params = crud._get_crud_params(self, insert_stmt, **kw)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/crud.py", line 100, in _get_crud_params
    _col_bind_name, check_columns, values, kw)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/crud.py", line 231, in _scan_cols
    implicit_returning, implicit_return_defaults, values, kw)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/crud.py", line 296, in _append_param_parameter
    value = compiler.process(value.self_group(), **kw)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 423, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw))
  File "/venv/lib/python3.6/site-packages/sqlalchemy/ext/compiler.py", line 460, in __call__
    "compilation handler." % type(element))
sqlalchemy.exc.CompileError: <class 'geoalchemy2.elements.WKBElement'> construct has no default compilation handler.
```

```
$ pip freeze
GeoAlchemy2==0.6.1
psycopg2-binary==2.7.7
Shapely==1.6.4.post2
SQLAlchemy==1.0.13
```

Here is an example that raises the error:
```
from geoalchemy2 import Geography
from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.orm import deferred, scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from geoalchemy2.shape import from_shape
from shapely.geometry import Polygon

Base = declarative_base()


class State(Base):
    __tablename__ = 'states'

    state_id = Column(Integer, primary_key=True, autoincrement=True)
    abbreviation = Column(String)
    name = Column(String)
    geom = deferred(Column('geom2', Geography(geometry_type='POLYGON', srid=4326)))
    new_geom = deferred(Column('geom3', Geography(geometry_type='MULTIPOLYGON', srid=4326)))


engine = create_engine('CONNECTIONSTRING')
session = scoped_session(sessionmaker(bind=engine))

state = State(
    abbreviation='MO2',
    name='Missouri2',
    geom=from_shape(Polygon([
        [
            -92.24817395210266,
            38.8320190082843
        ],
        [
            -92.249675989151,
            38.824831082702836
        ],
        [
            -92.22448468208313,
            38.824597045019544
        ],
        [
            -92.22838997840881,
            38.832085869301245
        ],
        [
            -92.24817395210266,
            38.832253021568874
        ],
        [
            -92.24817395210266,
            38.8320190082843
        ]]
    ))
)

session.add(state)
session.commit()
```

**Comment by elemoine** [comment]
Indeed, most of the GeoAlchemy2 tests fail with `sqlalchemy.exc.CompileError: <class …> construct has no default compilation handler` errors with SQLAlchemy 1.0.13.

**Comment by milkbread** [comment]
I've got the same problem on all versions >= 0.6.1 in combination with SQLAlchemy==1.0.19 & Python 3.7.3

Here is my example code:

`
from geoalchemy2 import Geometry
from sqlalchemy import Column

class JobLocationExternal(Model):
    __tablename__ = 'ext_job_location'
    bind_to = 'external_offer'

    id = Integer(primary_key=True)
    location = Text(nullable=False, default='')

    lat = Float(nullable=False)
    lng = Float(nullable=False)

    state = Text()
    county = Text()

    the_geom = Column(Geometry(geometry_type='POINT', srid=4326))`

**Comment by pkqs90** [comment]
I also encountered this issue, it works well with geoalchemy2 == 0.5.0, but not with versions >0.6.1. Any updates here?

**Comment by elemoine** [comment]
I haven't had time to look into this problem. And I won't be able to get to it before september. Feel free to create a PR for this if you know how to fix it.

**Comment by adrien-berchet** [comment]
Thanks for this report.
#242 (which is now merged in the master branch) should fix this issue (the code of @mam8cc works properly with these changes).
Reopen if you still have this issue in your use case.
