### ISSUE TITLE
Creating Geometry column fails for dimension=4 and management=True

### ISSUE THREAD

**Issue by damb** [geoalchemy/geoalchemy2#227]
Hi,

apparently `geoalchemy2` seems to fail while creating Geometry columns with `dimension=4` and `management=True`. 

* `SQLAlchemy==1.3.3`
* `GeoAlchemy2==0.6.2`
* `psycopg2-binary==2.8.2`
* PostgreSQL: ` PostgreSQL 9.6.9`
* PostGIS: `POSTGIS="2.4.4 r16526" PGSQL="96" GEOS="3.5.1-CAPI-1.9.1 r4246" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER`

Here's an example code:

```py
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, create_engine
from geoalchemy2 import Geometry

Base = declarative_base()

class Foo(Base):
    __tablename__ = 'foo'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    point = Column(Geometry(geometry_type='POINTZM', dimension=4,
                            management=True))

e = create_engine('postgres://foo:foo@localhost:5432/foo',
                  echo=True)

Base.metadata.create_all(e)
```

It fails with the following output:

```
2019-05-09 07:49:59,970 INFO sqlalchemy.engine.base.Engine select version()
2019-05-09 07:49:59,970 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 07:49:59,971 INFO sqlalchemy.engine.base.Engine select current_schema()
2019-05-09 07:49:59,971 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 07:49:59,972 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-05-09 07:49:59,972 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 07:49:59,972 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-05-09 07:49:59,972 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 07:49:59,973 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2019-05-09 07:49:59,973 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 07:49:59,974 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2019-05-09 07:49:59,974 INFO sqlalchemy.engine.base.Engine {'name': 'foo'}
2019-05-09 07:49:59,975 INFO sqlalchemy.engine.base.Engine
CREATE TABLE foo (
  id SERIAL NOT NULL,
  name VARCHAR,
  PRIMARY KEY (id)
)


2019-05-09 07:49:59,975 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 07:49:59,979 INFO sqlalchemy.engine.base.Engine COMMIT
2019-05-09 07:49:59,980 INFO sqlalchemy.engine.base.Engine SELECT AddGeometryColumn(%(AddGeometryColumn_2)s, %(AddGeometryColumn_3)s, %(AddGeometryColumn_4)s, %(AddGeometryColumn_5)s, %(AddGeometryColumn_6)s) AS "AddGeometryColumn_1"
2019-05-09 07:49:59,980 INFO sqlalchemy.engine.base.Engine {'AddGeometryColumn_2': 'foo', 'AddGeometryColumn_3': 'point', 'AddGeometryColumn_4': -1, 'AddGeometryColumn_5': 'POINTZM', 'AddGeometryColumn_6': 4}
2019-05-09 07:49:59,983 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.RaiseException: TypeM needs 3 dimensions
CONTEXT:  PL/pgSQL function addgeometrycolumn(character varying,character varying,character varying,character varying,integer,character varying,integer,boolean) line 39 at RAISE
SQL statement "SELECT public.AddGeometryColumn('','',$1,$2,$3,$4,$5, $6)"
PL/pgSQL function addgeometrycolumn(character varying,character varying,integer,character varying,integer,boolean) line 5 at SQL statement

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "create.py", line 17, in <module>
    Base.metadata.create_all(e)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4287, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 848, in visit_table
    _is_metadata_operation=_is_metadata_operation,
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/home/damb/work/projects/geoalchemy2/geoalchemy2/__init__.py", line 29, in after_create
    dispatch("after-create", target, connection)
  File "/home/damb/work/projects/geoalchemy2/geoalchemy2/__init__.py", line 98, in dispatch
    bind.execute(stmt)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/damb/work/projects/geoalchemy2/venv3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.RaiseException) TypeM needs 3 dimensions
CONTEXT:  PL/pgSQL function addgeometrycolumn(character varying,character varying,character varying,character varying,integer,character varying,integer,boolean) line 39 at RAISE
SQL statement "SELECT public.AddGeometryColumn('','',$1,$2,$3,$4,$5, $6)"
PL/pgSQL function addgeometrycolumn(character varying,character varying,integer,character varying,integer,boolean) line 5 at SQL statement

[SQL: SELECT AddGeometryColumn(%(AddGeometryColumn_2)s, %(AddGeometryColumn_3)s, %(AddGeometryColumn_4)s, %(AddGeometryColumn_5)s, %(AddGeometryColumn_6)s) AS "AddGeometryColumn_1"]
[parameters: {'AddGeometryColumn_2': 'foo', 'AddGeometryColumn_3': 'point', 'AddGeometryColumn_4': -1, 'AddGeometryColumn_5': 'POINTZM', 'AddGeometryColumn_6': 4}]
(Background on this error at: http://sqlalche.me/e/2j85)
```

However, with `management=False` it seems to work fine:

```
2019-05-09 08:05:50,252 INFO sqlalchemy.engine.base.Engine select version()
2019-05-09 08:05:50,252 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 08:05:50,253 INFO sqlalchemy.engine.base.Engine select current_schema()
2019-05-09 08:05:50,253 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 08:05:50,254 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-05-09 08:05:50,254 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 08:05:50,255 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-05-09 08:05:50,255 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 08:05:50,256 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2019-05-09 08:05:50,256 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 08:05:50,257 INFO sqlalchemy.engine.base.Engine select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where pg_catalog.pg_table_is_visible(c.oid) and relname=%(name)s
2019-05-09 08:05:50,257 INFO sqlalchemy.engine.base.Engine {'name': 'foo'}
2019-05-09 08:05:50,258 INFO sqlalchemy.engine.base.Engine 
CREATE TABLE foo (
        id SERIAL NOT NULL, 
        name VARCHAR, 
        point geometry(POINTZM,-1), 
        PRIMARY KEY (id)
)


2019-05-09 08:05:50,258 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 08:05:50,293 INFO sqlalchemy.engine.base.Engine COMMIT
2019-05-09 08:05:50,294 INFO sqlalchemy.engine.base.Engine CREATE INDEX "idx_foo_point" ON "public"."foo" USING GIST ("point")
2019-05-09 08:05:50,294 INFO sqlalchemy.engine.base.Engine {}
2019-05-09 08:05:50,295 INFO sqlalchemy.engine.base.Engine COMMIT
```

```
foo# \d foo
                                 Table "public.foo"
 Column |       Type        | Collation | Nullable |             Default             
--------+-------------------+-----------+----------+---------------------------------
 id     | integer           |           | not null | nextval('foo_id_seq'::regclass)
 name   | character varying |           |          | 
 point  | geometry(PointZM) |           |          | 
Indexes:
    "foo_pkey" PRIMARY KEY, btree (id)
    "idx_foo_point" gist (point)
```

**Comment by elemoine** [comment]
Indeed.

```
AddGeometryColumn('foo', 'point', -1, 'POINTZM', 4)
```

does not work in PostGIS, while

```
AddGeometryColumn('foo', 'point', -1, 'POINT', 4)
```

does work, and does add a `geometry(POINTZM)` geometry.

So you need to change the `geometry_type` to `POINT` from `POINTZM` in your Python code.

Hope this helps.

**Comment by elemoine** [comment]
> So you need to change the `geometry_type` to `POINT` from `POINTZM` in your Python code.

Hmm, but there may be a bug in GeoAlchemy preventing you from doing this. I'll check.

**Comment by damb** [comment]
@elemoine, thanks for having a look at this.

According to both the documentation of `geoalchemy2.types.Geography` and the [unittests](https://github.com/geoalchemy/geoalchemy2/blob/a50dd0f5c1d3af7befbbab53383712a89e495530/tests/test_types.py#L47-L77) `dimension=4` is exclusively allowed for geometries with a `ZM` suffix, which IMO makes absolutely sense. Else, you could create a geometry such as
```   
point = Column(Geometry(geometry_type='POINTZM', dimension=2))
```
which most probably will fail, too.

**Comment by elemoine** [comment]
The problem is that

```py
Geometry(geometry_type='POINT', dimension=4, management=True)
```

will faill today while it should not.

We need to rework that part I think.
