### ISSUE TITLE
(with sqlalchemy.future.Engine) sqlalchemy.exc.ObjectNotExecutableError

### ISSUE THREAD

**Issue by christophfink** [geoalchemy/geoalchemy2#297]
Creating a new ORM Mapped Class with an `sqlalchemy.future.Engine` fails with an `sqlalchemy.exc.ObjectNotExecutableError`

Example:
```
import geoalchemy2
import sqlalchemy
import sqlalchemy.ext.declarative
import sqlalchemy.orm


Base = sqlalchemy.ext.declarative.declarative_base()

class FlickrPhoto(Base):
    """ ORM class to represent a photo """
    __tablename__ = "photos"
    id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)
    geom = sqlalchemy.Column(geoalchemy2.Geometry("POINT", 4326))


engine = sqlalchemy.create_engine("postgresql://localhost/test", future=True)
Base.metadata.create_all(engine)
```

fails with:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1437, in _execute_20
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./example.py", line 17, in <module>
    Base.metadata.create_all(engine)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 4501, in create_all
    bind._run_ddl_visitor(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 348, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1939, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 486, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 729, in visit_metadata
    self.traverse_single(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 486, in traverse_single
    return meth(obj, **kw)
  File "/usr/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 795, in visit_table
    table.dispatch.after_create(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 264, in __call__
    fn(*args, **kw)
  File "/usr/lib/python3.8/site-packages/geoalchemy2/__init__.py", line 29, in after_create
    dispatch("after-create", target, connection)
  File "/usr/lib/python3.8/site-packages/geoalchemy2/__init__.py", line 112, in dispatch
    bind.execute('CREATE INDEX "idx_%s_%s" ON "%s" '
  File "/usr/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 286, in execute
    return self._execute_20(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1439, in _execute_20
    util.raise_(
  File "/usr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 180, in raise_
    raise exception
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'CREATE INDEX "idx_photos_geom" ON "photos" USING GIST ("geom")'
```

Using GeoAlchemy2-0.8.4 with the upcoming SQLAlchemy-1.4.0 on Python 3.8.6 in an ArchLinux environment

**Comment by adrien-berchet** [comment]
Hi @christophfink 
Thank you for this report. It might be related to #137 but I don't know much about the index part of `GeoAlchemy2`.
It seems that the error raised by sqlalchemy means that it does not accept queries as raw strings any more? I will try check that when I have some time.

**Comment by christophfink** [comment]
So it seems: 

 ```
         :param statement: The statement to be executed.  This is always
           an object that is in both the :class:`_expression.ClauseElement` and
           :class:`_expression.Executable` hierarchies, including:
  
           * :class:`_expression.Select`
           * :class:`_expression.Insert`, :class:`_expression.Update`,
             :class:`_expression.Delete`
           * :class:`_expression.TextClause` and
             :class:`_expression.TextualSelect`
           * :class:`_schema.DDL` and objects which inherit from
             :class:`_schema.DDLElement`

```
(that’s from future/engine.py:254)

A workaround for now is to simply not use the `future` features (next-gen ORM syntax can be used with it), but this potentially breaks things in the future.
