### ISSUE TITLE
Using Geoalchemy2, Alembic and tables with ForeignKey

### ISSUE THREAD

**Issue by eugene-raiser** [geoalchemy/geoalchemy2#397]
I tried to run generate tables migration with foreign key using alembic and got an error

```text
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'group'
INFO  [alembic.autogenerate.compare] Detected added table 'item'
INFO  [alembic.autogenerate.compare] Detected added index 'idx_item_geom' on '['geom']'
Traceback (most recent call last):
  File "venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "venv/lib/python3.9/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "venv/lib/python3.9/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "venv/lib/python3.9/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "venv/lib/python3.9/site-packages/alembic/command.py", line 236, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "venv/lib/python3.9/site-packages/alembic/command.py", line 236, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 606, in generate_scripts
    yield self._to_script(generated_revision)
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/api.py", line 506, in _to_script
    render._render_python_into_templatevars(
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/render.py", line 83, in _render_python_into_templatevars
    _render_cmd_body(upgrade_ops, autogen_context)
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/render.py", line 108, in _render_cmd_body
    lines = render_op(autogen_context, op)
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/render.py", line 126, in render_op
    lines = util.to_list(renderer(autogen_context, op))
  File "venv/lib/python3.9/site-packages/geoalchemy2/alembic_helpers.py", line 445, in render_create_geo_table
    table_render = _add_table(autogen_context, op)
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/render.py", line 228, in _add_table
    for rcons in [
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/render.py", line 229, in <listcomp>
    _render_constraint(
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/render.py", line 932, in _render_constraint
    return renderer(constraint, autogen_context, namespace_metadata)
  File "venv/lib/python3.9/site-packages/alembic/autogenerate/render.py", line 1033, in _render_foreign_key
    apply_metadata_schema = namespace_metadata.schema
AttributeError: 'NoneType' object has no attribute 'schema'
```

# How to reproduce

## requirements.txt

```requirements.txt
asyncpg==0.26.0
sqlalchemy==1.4.40
alembic==1.8.1
geoalchemy2==0.12.3
```

## main.py

```python
from sqlalchemy.orm import declarative_base
from sqlalchemy import Column, Integer, String, ForeignKey
from geoalchemy2.types import Geometry

Base = declarative_base()


class Item(Base):
    __tablename__ = 'item'
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String)
    group_id = Column(Integer, ForeignKey('group.id'))
    geom = Column(Geometry())


class Group(Base):
    __tablename__ = 'group'
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String)
```

### Create template

```shell
alembic init --template async alembic 
```

### Edit `alembic/env.py`

```python
from geoalchemy2 import alembic_helpers

import main  # noqa

...


def run_migrations_offline() -> None:
    ...
    context.configure(
        ...,
        process_revision_directives=alembic_helpers.writer,
        render_item=alembic_helpers.render_item,
        include_object=alembic_helpers.include_object,
    )


...


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        ...,
        process_revision_directives=alembic_helpers.writer,
        render_item=alembic_helpers.render_item,
        include_object=alembic_helpers.include_object,
    )
```

### Init migration

```shell
alembic init --template async migrations
```

# How to fix

You need to replace the lines in the `create_geo_table` function of the `alembic_helpers` module

```python
new_op = CreateGeospatialTableOp(op.table_name, op.columns, op.schema)
```

with

```python
new_op = CreateGeospatialTableOp(
    op.table_name,
    op.columns,
    op.schema,
    op._namespace_metadata,
    op._constraints_included
)
```

The result should be like

```python
@writer.rewrites(ops.CreateTableOp)
def create_geo_table(context, revision, op):
    ...

    if gis_cols:
        new_op = CreateGeospatialTableOp(
            op.table_name,
            op.columns,
            op.schema,
            op._namespace_metadata,
            op._constraints_included
        )
    ...
```

**Comment by adrien-berchet** [comment]
Hi @eugene-raiser 
Thank you very much for this very detailed report and to provide a fix!
I created a PR (#398) with your fix and updated tests to check migrations with foreign keys. It looks good to me but maybe you can try on your full use case to check it fixes everything you need?

**Comment by eugene-raiser** [comment]
Hi. Thanks for the quick reply. So far I haven't found any other issues. If I run into any issues, I'll post it here

**Comment by adrien-berchet** [comment]
Ok, thanks. I merged #398.
Do you want a new release now or do you want some more time to do more testing?

**Comment by eugene-raiser** [comment]
I made a patch and am using it instead of alembic_helpers so I can wait for the new release.

```python
from geoalchemy2.alembic_helpers import writer, ops, Geography, Geometry, Raster, CreateGeospatialTableOp, \
    _get_gis_cols, render_item, include_object

del writer.dispatch._registry[(ops.CreateTableOp, 'default')]


@writer.rewrites(ops.CreateTableOp)
def create_geo_table_patch(context, revision, op):
    """Replace the default CreateTableOp by a geospatial-specific one."""
    dialect = context.bind.dialect
    gis_cols = _get_gis_cols(
        op, (Geometry, Geography, Raster), dialect, check_col_management=False
    )

    if gis_cols:
        new_op = CreateGeospatialTableOp(
            op.table_name,
            op.columns,
            op.schema,
            op._namespace_metadata,
            op._constraints_included
        )
    else:
        new_op = op

    return new_op
```

**Comment by adrien-berchet** [comment]
Ok, I see. I will wait a few days before releasing then, just in case you would find any other issue.

**Comment by hochstibe** [comment]
I have the same issue, a release would be appreciated :-)

**Comment by adrien-berchet** [comment]
Ups, sorry, I completely forgot about that :sweat_smile: 
Let's release a new version!

**Comment by adrien-berchet** [comment]
@hochstibe @eugene-raiser : https://pypi.org/project/GeoAlchemy2/0.12.4/
