### ISSUE TITLE
Autogeneration fails due to missing Namespace Metadata

### ISSUE THREAD

**Issue by mmittel3** [geoalchemy/geoalchemy2#406]
Hey folks,
I have troubles autogenerating the initial alembic migration script using flask migrate:
```
Traceback (most recent call last):
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/flask_migrate/cli.py", line 91, in migrate
    _migrate(directory, message, sql, head, splice, branch_label, version_path,
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 210, in migrate
    command.revision(config, message, autogenerate=True, sql=sql,
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/command.py", line 236, in revision
    scripts = [script for script in revision_context.generate_scripts()]
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/command.py", line 236, in <listcomp>
    scripts = [script for script in revision_context.generate_scripts()]
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 606, in generate_scripts
    yield self._to_script(generated_revision)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/api.py", line 506, in _to_script
    render._render_python_into_templatevars(
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/render.py", line 83, in _render_python_into_templatevars
    _render_cmd_body(upgrade_ops, autogen_context)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/render.py", line 108, in _render_cmd_body
    lines = render_op(autogen_context, op)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/render.py", line 126, in render_op
    lines = util.to_list(renderer(autogen_context, op))
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/geoalchemy2/alembic_helpers.py", line 419, in render_create_geo_table
    table_render = _add_table(autogen_context, op)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/render.py", line 229, in _add_table
    for rcons in [
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/render.py", line 230, in <listcomp>
    _render_constraint(
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/render.py", line 934, in _render_constraint
    return renderer(constraint, autogen_context, namespace_metadata)
  File "/Users/mmi/WIND_InfraAnalytics/server/venv/lib/python3.8/site-packages/alembic/autogenerate/render.py", line 1035, in _render_foreign_key
    apply_metadata_schema = namespace_metadata.schema
AttributeError: 'NoneType' object has no attribute 'schema'
```
Apparently the `CreateGeospatialTableOp` instance is created with `_namespace_metadata` set to `None`. For one of my tables alembic is trying to create a foreign key constraint `ForeignKeyConstraint(<sqlalchemy.sql.base.DedupeColumnCollection, ...` which fails due to the missing metadata. This is the definition of the failing table:
```
t_restriction_ticket = Table(
    "restriction_ticket",
    metadata,
    Column(
        "ticket_id",
        Integer,
        primary_key=True,
        autoincrement=True,
        nullable=False,
        unique=True,
    ),
    Column("project_id", Integer, nullable=True),
    Column("regional_planning", String, nullable=False),
    Column("suitability", String, nullable=False),
    Column("description", String, nullable=False),
    Column("further_info", String, nullable=True),
    Column("geom", Geometry("POLYGON"), nullable=False),
    # UserCreatedMixin
    Column("user_id", Integer, ForeignKey("user.id"), nullable=False),
    Column("created_by", String, nullable=False),
    Column(
        "date_created", DateTime, nullable=False, default=datetime.now(timezone.utc)
    ),
    Column("last_edited_by", String, nullable=True),
    Column("date_edited", DateTime, nullable=True),
    schema="wind",
)
```
I found a way, to work around this problem, using this patch:
```
--- alembic_helpers.py.orig     2022-10-10 09:24:20.000000000 +0200
+++ alembic_helpers.py  2022-10-10 09:24:30.000000000 +0200
@@ -436,7 +436,7 @@
     )
 
     if gis_cols:
-        new_op = CreateGeospatialTableOp(op.table_name, op.columns, op.schema)
+        new_op = CreateGeospatialTableOp(op.table_name, op.columns, op.schema, _namespace_metadata=op._namespace_metadata)
     else:
         new_op = op
```
But I have no clue, why it is necessary and if I break something doing this.

**Comment by adrien-berchet** [comment]
Hi @mmittel3 
Thank you for this report!
Could you please check that you use the latest version of `GeoAlchemy2` please (version `0.12.5`)? I think this was already fixed in this version.

**Comment by mmittel3** [comment]
Wow, the upgrade solves all my problems. Life can be so easy 😅 Thanks for the quick reply.

**Comment by adrien-berchet** [comment]
Ahah cool :smile: 
Have fun with `GeoAlchemy2` then :-)
