### ISSUE TITLE
[How to use] GeoAlchemy ORM with MySQL

### ISSUE THREAD

**Issue by tebrown** [geoalchemy/geoalchemy2#490]
### Describe the problem

I cannot figure out how to use the MySQL dialect with the GeoAlchemy ORM.  When I try, it always generates a compile error because I am not using the value in a function call

### Show what you tried to do.

```Python
import asyncio
from dictalchemy import DictableModel

from sqlalchemy import String
from sqlalchemy import JSON
from sqlalchemy.ext.asyncio import AsyncAttrs
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import MappedAsDataclass
from sqlalchemy.ext.asyncio import async_sessionmaker
from sqlalchemy.ext.asyncio import create_async_engine
from geoalchemy2 import WKBElement, Geometry
from geoalchemy2.types import select_dialect

engine = create_async_engine("mariadb+asyncmy://user:password@mariadb/db")
async_session = async_sessionmaker(engine, expire_on_commit=False)

class Base(DictableModel, AsyncAttrs, DeclarativeBase):
    pass

class LocationAlerts(MappedAsDataclass, Base):
    __tablename__ = "location_alerts"
    psap: Mapped[str] = mapped_column(String(64), nullable=False, primary_key=True)
    dst_agency: Mapped[str] = mapped_column(String(32), nullable=False)
    units: Mapped[dict] = mapped_column(JSON, nullable=False)
    mapped_geom: Mapped[WKBElement] = mapped_column(Geometry)


async def async_main():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

if __name__ == "__main__":
    asyncio.run(async_main())
```

### Describe what you expected.

This should generate the SQL 

```sql
CREATE TABLE location_alerts (
	psap VARCHAR(64) NOT NULL, 
	dst_agency VARCHAR(32) NOT NULL, 
	units JSON NOT NULL, 
        mapped_geo geometry NOT NULL, 
	PRIMARY KEY (psap)
)
```

but instead generates the PGSQL version:
```sql
CREATE TABLE location_alerts (
	psap VARCHAR(64) NOT NULL, 
	dst_agency VARCHAR(32) NOT NULL, 
	units JSON NOT NULL, 
	mapped_geom geometry(GEOMETRY,-1) NOT NULL, 
	PRIMARY KEY (psap)
)
```

### Error

```Python traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 92, in execute
    return self.await_(self._execute_async(operation, parameters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 127, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/mysql/asyncmy.py", line 104, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncmy/cursors.pyx", line 179, in execute
  File "asyncmy/cursors.pyx", line 364, in _query
  File "asyncmy/connection.pyx", line 494, in query
  File "asyncmy/connection.pyx", line 682, in _read_query_result
  File "asyncmy/connection.pyx", line 1069, in read
  File "asyncmy/connection.pyx", line 644, in read_packet
  File "asyncmy/protocol.pyx", line 190, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/protocol.pyx", line 194, in asyncmy.protocol.MysqlPacket.raise_for_error
  File "asyncmy/errors.pyx", line 128, in asyncmy.errors.raise_mysql_exception
  File "asyncmy/errors.pyx", line 137, in asyncmy.errors.raise_mysql_exception
asyncmy.errors.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'GEOMETRY,-1) NOT NULL, \n\tPRIMARY KEY (psap)\n)' at line 5")
```
```


### Additional context

Running Python 3.11, Arch Linux.  SQL DB is MariaDB 11.2.2, which is compatible with MySQL 8.0

### GeoAlchemy 2 Version in Use

0.14.4

**Comment by adrien-berchet** [comment]
Hi @tebrown 
Thanks for your report!
Indeed, the `mariadb` dialect is not supported so a default query is generated. I don't know MariaDB but the queries are the same as the MySQL ones it's very easy to add support for it. I don't have any MariaDB instance to test but if you want to test (or even open a PR for it) I think you just have to change the following in `geoalchemy/admin/__init__.py`:
```python
def select_dialect(dialect_name):
    """Select the dialect from its name."""
    known_dialects = {
        "geopackage": dialects.geopackage,
        "mysql": dialects.mysql,
        "postgresql": dialects.postgresql,
        "sqlite": dialects.sqlite,
    }
    return known_dialects.get(dialect_name, dialects.common)
```
into this:
```python
def select_dialect(dialect_name):
    """Select the dialect from its name."""
    known_dialects = {
        "geopackage": dialects.geopackage,
        "mariadb": dialects.mysql,
        "mysql": dialects.mysql,
        "postgresql": dialects.postgresql,
        "sqlite": dialects.sqlite,
    }
    return known_dialects.get(dialect_name, dialects.common)
```

**Comment by tebrown** [comment]
Hi @adrien-berchet! 

  Thanks!  I will definitely open a MR for mariadb, but I am just not sure HOW to use the dialect. Is it picked automatically based on the connection sting?

**Comment by tebrown** [comment]
Seem so!  If I change my connection string to `mysql+asyncmy://user:pass@mariadb/db`, it does generate the right SQL.  I did try to update the `select_dialect` function, but it didn't work right. I am pretty sure it's a me problem though.  Once I get that all figured out, I will make a PR. Thank you very much!

**Comment by adrien-berchet** [comment]
Great!
From your example you should be able to retrieve the proper name with `engine.dialect.name`. That's how we chose the proper dialect in GeoAlchemy 2.

**Comment by tebrown** [comment]
Great!  I am starting to figure this out!  I appreciate the help!

**Comment by adrien-berchet** [comment]
You're welcome :⁠-⁠)
